/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as GithubRouteImport } from './routes/github'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemDesignRouteImport } from './routes/system-design'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth.github.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDesignRoute = SystemDesignRouteImport.update({
  id: '/system-design',
  path: '/system-design',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/books': typeof BooksRoute
  '/coding': typeof CodingRoute
  '/github': typeof GithubRoute
  '/interview': typeof InterviewRoute
  '/journal': typeof JournalRoute
  '/knowledge': typeof KnowledgeRoute
  '/mission': typeof MissionRoute
  '/projects': typeof ProjectsRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/system-design': typeof SystemDesignRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/books': typeof BooksRoute
  '/coding': typeof CodingRoute
  '/github': typeof GithubRoute
  '/interview': typeof InterviewRoute
  '/journal': typeof JournalRoute
  '/knowledge': typeof KnowledgeRoute
  '/mission': typeof MissionRoute
  '/projects': typeof ProjectsRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/system-design': typeof SystemDesignRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/books': typeof BooksRoute
  '/coding': typeof CodingRoute
  '/github': typeof GithubRoute
  '/interview': typeof InterviewRoute
  '/journal': typeof JournalRoute
  '/knowledge': typeof KnowledgeRoute
  '/mission': typeof MissionRoute
  '/projects': typeof ProjectsRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/system-design': typeof SystemDesignRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/analytics'
    | '/books'
    | '/coding'
    | '/github'
    | '/interview'
    | '/journal'
    | '/knowledge'
    | '/mission'
    | '/projects'
    | '/roadmap'
    | '/security'
    | '/settings'
    | '/system-design'
    | '/auth/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/books'
    | '/coding'
    | '/github'
    | '/interview'
    | '/journal'
    | '/knowledge'
    | '/mission'
    | '/projects'
    | '/roadmap'
    | '/security'
    | '/settings'
    | '/system-design'
    | '/auth/github/callback'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/analytics'
    | '/books'
    | '/coding'
    | '/github'
    | '/interview'
    | '/journal'
    | '/knowledge'
    | '/mission'
    | '/projects'
    | '/roadmap'
    | '/security'
    | '/settings'
    | '/system-design'
    | '/auth/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BooksRoute: typeof BooksRoute
  CodingRoute: typeof CodingRoute
  GithubRoute: typeof GithubRoute
  InterviewRoute: typeof InterviewRoute
  JournalRoute: typeof JournalRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MissionRoute: typeof MissionRoute
  ProjectsRoute: typeof ProjectsRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SystemDesignRoute: typeof SystemDesignRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-design': {
      id: '/system-design'
      path: '/system-design'
      fullPath: '/system-design'
      preLoaderRoute: typeof SystemDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  BooksRoute: BooksRoute,
  CodingRoute: CodingRoute,
  GithubRoute: GithubRoute,
  InterviewRoute: InterviewRoute,
  JournalRoute: JournalRoute,
  KnowledgeRoute: KnowledgeRoute,
  MissionRoute: MissionRoute,
  ProjectsRoute: ProjectsRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SystemDesignRoute: SystemDesignRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
